sonar.projectKey=DemExt_python-project-52
sonar.organization=demext
sonar.sources=.
sonar.python.version=3.14
sonar.exclusions=**/migrations/**, **/tests.py, manage.py
sonar.python.coverage.reportPaths=coverage.xml