name: Build and Analysis
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies and run tests
        run: |
          pip install uv
          uv sync
          # Устанавливаем coverage, если его нет в зависимостях
          uv pip install coverage
          # Установка Chromium и системных библиотек для него
          npx playwright install --with-deps chromium 
          # Генерируем данные о покрытии
          uv run coverage run manage.py test
          # Превращаем их в XML-отчет
          uv run coverage xml

      - name: SonarQube Cloud Scan
        # Используем новую версию, как просил линтер в логах
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}